title: "옝옝코딩"
description: "전부 공부할거야"
author: yeyein
avatar: /img_02.jpg
email: yeiny0301@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: img_02.jpg
social:
  name: "박예인"
  links:
    - https://github.com/yeyein
lang: ko-KR
